name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set version variables
        run: |
          VER=$(grep appVersion charts/fastapi-hw/Chart.yaml |cut -d '"' -f2)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DH_USER }}/fastapi-hw
          tags: |
            type=ref,event=branch,enable=true,priority=600
            type=ref,event=pr,prefix=pr-,enable=true,priority=600
            type=pep440,pattern={{version}},value={{ env.VERSION }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
